LoggingFileName: "Log.txt"

Loading:
  Model_name: "QuantizedFloat16.pt"
  TokenizerDir: "TokenizerDir/"

Generate:
  context_max_len: 512
  summary_max_len: 128
  num_beams: 2
  repetition_penalty: 2.5
  length_penalty: 1.0
  early_stopping: True


